### ISSUE TITLE
ON./ON/OFF

### ISSUE THREAD

**Issue by 1j01** [zz85/zz85-bookmarklets#10]
Auto-Refresh Values starts at <kbd>ON</kbd>**.** then when you click it, it goes to <kbd>ON</kbd>, and then it toggles to <kbd>OFF</kbd>/<kbd>ON</kbd>

**Comment by zz85** [comment]
I noticed that too... will try to fix it soon!

**Comment by zz85** [comment]
thanks @1j01, should be fixed. let me know if otherwise! :)
